spring:
  mail:
    host: smtp.naver.com
    port: 465
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            enable: enable
    username: tjdfkr011
    password: ssikssik330&
front:
  server: 172.20.10.3:3000