INSERT INTO "symbol" ("symbol_name", "symbol_img_name", "symbol_code", "symbol_condition_cnt") VALUES
	('1레벨 : AQuh 에 오신걸 환영합니다!', 'lv1.png', 'exp_cnt', 0),
	('2레벨 : 뉴비를 벗어나다', 'lv2.png', 'exp_cnt', 1000),
	('3레벨 : AQuh를 즐기는', 'lv3.png', 'exp_cnt', 2500),
	('4레벨 : AQuh 주민', 'lv4.png', 'exp_cnt', 4500),
	('5레벨 : AQuh 마스터', 'lv5.png', 'exp_cnt', 7000),
	('6레벨 : AQuh 고인물', 'lv6.png', 'exp_cnt', 10000),
	('버블 입문자', 'bb1.png', 'bubble_join_cnt', 1),
	('버블 이용자', 'bb2.png', 'bubble_join_cnt', 5),
	('버블 중견 이용자', 'bb3.png', 'bubble_join_cnt', 10),
	('버블을 즐기는', 'bb4.png', 'bubble_join_cnt', 20),
	('버블 마스터', 'bb5.png', 'bubble_join_cnt', 50),
	('버블 고인물', 'bb6.png', 'bubble_join_cnt', 100),
	('첫 베스트 멤버', 'Man_Standing.png', 'best_cnt', 1),
	('베스트 멤버에 익숙해진', 'Man_walking.png', 'best_cnt', 10),
	('베스트 멤버 마스터', 'Man_Running.png', 'best_cnt', 50),
	('AQua 베스트 멤버', 'Man_Dancing.png', 'best_cnt', 100),
	('피드를 시작한', 'p1.png', 'feed_cnt', 1),
	('피드를 즐겨 쓰는', 'p2.png', 'feed_cnt', 10),
	('피드에 할 말이 많은', 'p3.png', 'feed_cnt', 50),
	('피드 마스터', 'p4.png', 'feed_cnt', 200),
	('짝사랑', 'l1.png', 'like_give_cnt', 1),
	('좋아요를 누르기 시작한', 'l2.png', 'like_give_cnt', 10),
	('좋은 것들이 많아서', 'l3.png', 'like_give_cnt', 50),
	('적극적인 좋아요 표현', 'l4.png', 'like_give_cnt', 100),
	('AQuh를 좋아하는', 'l5.png', 'like_give_cnt', 200),
	('첫사랑', 'll1.png', 'like_receive_cnt', 1),
	('좋아요를 받기 시작한', 'll2.png', 'like_receive_cnt', 10),
	('좋아요를 많이 받은', 'll3.png', 'like_receive_cnt', 50),
	('수 많은 좋아요', 'll4.png', 'like_receive_cnt', 100),
	('AQuh 아이돌', 'll5.png', 'like_receive_cnt', 200),
	('팔로잉 시작', 'fg1.png', 'following_cnt', 1),
	('팔로잉을 즐기는', 'fg2.png', 'following_cnt', 10),
	('수 많은 팔로잉', 'fg3.png', 'following_cnt', 50),
	('팔로잉 마스터', 'fg4.png', 'following_cnt', 100),
	('AQuh를 팔로잉', 'fg5.png', 'following_cnt', 200),
	('팔로워 시작', 'fr1.png', 'follower_cnt', 1),
	('팔로워를 거느린', 'fr2.png', 'follower_cnt', 10),
	('수 많은 팔로워들', 'fr3.png', 'follower_cnt', 50),
	('팔로워 마스터', 'fr4.png', 'follower_cnt', 100),
	('AQuh 인플루언서', 'fr5.png', 'follower_cnt', 200),
	('스포츠/운동', '스포츠/운동.png', 'category', 10),
	('수공예/드로잉', '수공예/드로잉.png', 'category', 10),
	('요리/베이킹', '요리/베이킹.png', 'category', 10),
	('문화/예술', '문화/예술.png', 'category', 10),
	('미용/뷰티', '미용/뷰티.png', 'category', 10),
	('홈/리빙', '홈/리빙.png', 'category', 10),
	('자기개발', '자기개발.png', 'category', 10),
	('기타', '기타.png', 'category', 10);