yarnPath: .yarn/releases/yarn-3.6.1.cjs
nodeLinker: "node-modules"
packageExtensions:
  'jest-util@*':
    dependencies:
      'process': '^0.11.10'
      'url': '^0.11.1'
  react-scripts@*:
    peerDependencies:
      eslint-config-react-app: "*"
