FROM node:18-alpine
WORKDIR /app

COPY .yarn/ .yarnrc.yml yarn.lock package.json package-lock.json /app 
RUN corepack enable && corepack prepare yarn@stable --activate && yarn set version 3.3.0 && yarn install
COPY . .

EXPOSE 3000

CMD yarn start
